apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: goofy-cdn
type: Opaque
stringData:
  mongodb-uri: "mongodb+srv://root:KHQwwlpkRkj2Gss1@hetic-cdn.w3j7f.mongodb.net/?retryWrites=true&w=majority&appName=hetic-cdn"
  jwt-secret: "local-development-secret"
---
apiVersion: v1
kind: Secret
metadata:
  name: monitoring-secrets
  namespace: monitoring
type: Opaque
stringData:
  grafana-admin-password: "admin"
